### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by daniyo27** [gogo2/nuitrack-osceleton#1]
Hey there! 
Stumbled upon your repo and tried to compile after generating CMake project files and couldn't compile the program with Visual Studio 2019. Any steps I am missing? 

Compiler complains of missing file "lo/lo.h" -- In the directory there is only lo.h.in

Could you please help? Thanks! Would really love to try this out!

**Comment by bsobol** [comment]
I don't use Visual Studio, but.. lo.h should be generated during cmake project loading. It probably is there somewhere, where VS decided to put it. You can try to find it and move to `/lib/liblo-0.30/lo`

If you won't succeed I will try to have a look myself. Let me know.
